name: Punch In

on:
  schedule:
    - cron: '55 0 * * *'  # 台北時間 08:55
    - cron: '55 8 * * *'  # 台北時間 16:55
  workflow_dispatch:  # 手動觸發

jobs:
  punch_in:
    runs-on: ubuntu-20.04
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}
    steps:
      - name: "checkout"
        uses: actions/checkout@v1
      - name: "Punch in"
        run: ./punch_in
